### ISSUE TITLE
KeyError: ''

### ISSUE THREAD

**Issue by dcuddeback** [honza/vim2pygments#2]
I get the following error when trying to convert `jellybeans.vim` (version 1.4 or 1.5, available here http://www.vim.org/scripts/script.php?script_id=2555):

```
$ python vimpygments.py ~/.vim/colors/jellybeans.vim > jellybeans.py
Traceback (most recent call last):
  File "vimpygments.py", line 935, in <module>
    sys.exit(main() or 0)
  File "vimpygments.py", line 930, in main
    convert(filename, sys.stdout)
  File "vimpygments.py", line 914, in convert
    writer.write(out)
  File "vimpygments.py", line 883, in write
    default_token, tokens = find_colors(self.code)
  File "vimpygments.py", line 862, in find_colors
    default_token = color_map.pop('')
KeyError: ''
```

**Comment by honza** [comment]
I had a quick look at the theme in question and it looks like it's one of those
themes that this utility doesn't understand.  Another popular theme that we
can't convert is solarized.

I hate to give you a bullshit answer but I'm not sure exactly how this script
works since I'm not the original author.  I simply fixed one or two things that
bugged me and put it up on Github.

If you feel like digging through the Python code and happen to find the bug,
please let me know and we can include the fix.  However,  I don't suspect that
you will feel up to it.

**Comment by dcuddeback** [comment]
No worries. I did poke at the Python code for a bit, but didn't uncover anything. I ended up selecting a different theme, because I'm doing this for the web and I want a theme with a light background. It works fine with the other theme I'm using. I was just trying `jellybeans.vim` to get something working, and I thought I'd report a bug that I found.

**Comment by twe4ked** [comment]
> I was just trying jellybeans.vim to get something working, and I thought I'd report a bug that I found.

I had the same issue using jellybeans.

I opened Vim with the colorscheme loaded then ran the following commands (thanks @nathanaelkane):

```
redir >> /tmp/tmp.vim
exec 'silent hi'
redir END
```

I then edited `/tmp/tmp.vim` and added `hi` to the start of each line. I then ran the resulting file through `vimpygments.py`.
